# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  #lancement des test
  run-test:
    docker:
      -image: cimg/base:current
    steps:
      - checkout
      - run :
        name : "run test"
        command : mvn test

  # Job for uploading to Codecov
  codecov-upload:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Upload coverage to Codecov"
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  

# Orchestrate jobs using workflows
workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - run-test
      - codecov-upload

# Orbs
orbs:
  codecov: codecov/codecov@4.0.1

# Environment variables
env:
  CODECOV_TOKEN: 75ca8560-c635-4c2a-bb2f-316a0f546dd0
