# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # Lancement des tests
  run-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: |
            mvn test

  # Lancement de Checkstyle
  run-checkstyle:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Run Checkstyle"
          command: |
            mvn checkstyle:check
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-report

  # Génération de la documentation avec Maven Site
  generate-docs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Generate Maven site"
          command: |
            mvn site
      - store_artifacts:
          path: target/site/
          destination: site-docs
          
  # Job for uploading to Codecov
  codecov-upload:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: mvn test
      - codecov/upload:
          token: $CODECOV_TOKEN
          file: target/jacoco.exec
  
  # Test de variable token
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Test environment variable"
          command: "echo $CODECOV_TOKEN"
            
# Orchestrate jobs using workflows
workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - run-test
      - run-checkstyle:
          requires:
            - run-test
      - generate-docs:
          requires:
            - run-test
      - test
      - codecov-upload:
          requires:
            - run-test

# Orbs
orbs:
  codecov: codecov/codecov@4.0.1

# Environment variables
env:
  CODECOV_TOKEN: 75ca8560-c635-4c2a-bb2f-316a0f546dd0
